# Generated by Django 5.1.7 on 2025-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tarea',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
