# Generated by Django 5.1.7 on 2025-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion_app', '0002_persona_tarea_alter_persona_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tarea',
            field=models.CharField(choices=[('PREP', 'Preparación del terreno'), ('FUND', 'Fundaciones y cimentaciones'), ('ESTR', 'Estructura'), ('ALBA', 'Albañilería y acabados'), ('INST', 'Instalaciones: Eléctricas, Plomería, HVAC'), ('PINT', 'Pintura y decoración'), ('PAIS', 'Paisajismo y exteriores'), ('SUPE', 'Supervisión y control de calidad')], default='PREP', max_length=4, verbose_name='Tarea asignada'),
        ),
    ]
